config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  get 'errors/500' => 'errors#raise'
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  belongs_to :user

  validates :title, :price, :description, presence: true

  pg_search_scope :search_for, against: %i(title description)

  mount_uploader :image, ImageUploader

  validate :image_size_validation

  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_raven_context

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def raise
    raise 'Error'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = @products.search_for(params[:search]) if params[:search].present?
    @products = @products.page(params[:page]).per(40)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = current_user.products.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSampleShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="container">
        <ul class="menu">
          <li>
            <%= link_to 'Home', root_path %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to 'New Product', new_product_path %>
            </li>
            <li>
              <%= current_user.email %>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            </li>
          <% else %>
            <li>
              <%= link_to('Login', new_user_session_path) %>
            </li>
            <li>
              <%= link_to('Sign up', new_user_registration_path) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <%- if notice %>
        <p id="notice" class="notice"><%= notice %></p>
      <% end %>

      <%- if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <div class="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 6, cols: 50 %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <small>Max 100KB</small>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<hr/>

<div class="component">
  <% if user_signed_in? %>
    <%= link_to 'New Product', new_product_path %>
  <% end %>
</div>

<div class="component">
  <%= form_tag(products_path, method: :get) do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search' %>
  <% end %>
</div>


<table class="products-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th>Created</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product %></td>
        <td><%= truncate product.description %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= image_tag(product.image_url, height: 64) if product.image? %></td>
        <td><%= product.created_at.to_s(:short) %></td>
        <%- if product.user == current_user %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h2>
  <%= @product.title %>
</p>
<hr/>

<h3>
  <strong>Price:</strong>
  <%= number_to_currency @product.price %>
</h3>

<div>
  <%= simple_format @product.description %>
</div>

<div>
  <%= image_tag(@product.image_url) if @product.image? %>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>